class window.ElementsRepositoryService
  constructor: ()->
    @loadDefaults()

  loadDefaults: ()->
    @all = []

    @all.push new Element("Price", "AUD", "major") 
    @all.push new Element("Energy", "kilocalorie", "macro") 
    @all.push new Element("Protein", "g", "macro") 
    @all.push new Element("Carbohydrates", "g", "macro") 
    @all.push new Element("Carbohydrates (sugars)", "g", "breakdown") 
    @all.push new Element("Fats", "g", "macro") 
    @all.push new Element("Fats (saturated)", "g", "breakdown") 
    @all.push new Element("Fats (monounsaturated)", "g", "breakdown")
    @all.push new Element("Fats (polyunsaturated)", "g", "breakdown")
    @all.push new Element("Fibre", "g", "major") 
    @all.push new Element("Sodium", "mg", "major", new Qty("920mg"), new Qty("2300mg")) 
    @all.push new Element("Potassium", "g", "major", new Qty("1950mg"), new Qty("5460mg")) 
    @all.push new Element("Calcium", "g", "major") 
    @all.push new Element("Chlorine", "g", "minor") 
    @all.push new Element("Iron", "mg", "minor", new Qty("15 microgram"), new Qty("200mg")) # Poison at 40mg/kg, but did 10% of 50kg just in case
    @all.push new Element("Phosphorus", "g", "minor") 
    @all.push new Element("Iodine", "microgram", "minor") 
    @all.push new Element("Magnesium", "mg", "minor") 
    @all.push new Element("Zinc", "mg", "minor") 
    @all.push new Element("Selenium", "microgram", "minor", new Qty("400 microgram") ) 
    @all.push new Element("Copper", "mg", "minor") 
    @all.push new Element("Manganese", "mg", "minor") 
    @all.push new Element("Chromium", "microgram", "minor") 
    @all.push new Element("Molybdenum", "microgram", "minor") 
    @all.push new Element("Vitamin A", "IU", "minor") 
    @all.push new Element("Vitamin B6", "mg", "minor") 
    @all.push new Element("Vitamin B12", "microgram", "minor") 
    @all.push new Element("Vitamin C", "mg", "minor") 
    @all.push new Element("Vitamin D", "IU", "minor") 
    @all.push new Element("Vitamin E", "IU", "minor") 
    @all.push new Element("Vitamin K", "microgram", "minor") 
    @all.push new Element("Thiamin", "mg", "minor") 
    @all.push new Element("Riboflavin", "mg", "minor") 
    @all.push new Element("Niacin", "mg", "minor") 
    @all.push new Element("Folate", "microgram", "minor") 
    @all.push new Element("Biotin", "microgram", "minor") 
    @all.push new Element("Pantothenic acid", "mg", "minor") 
    @all.push new Element("Choline", "g", "minor") 
    @all.push new Element("Sulfur", "g", "minor") 
    @all.push new Element("Lithium", "microgram", "minor") 
    @all.push new Element("Creatine", "g", "minor") 
    @all.push new Element("Lycopene", "microgram", "minor") 
    @all.push new Element("Omega-3 Fatty Acids", "mg", "minor") 
    @all.push new Element("Ginseng", "microgram", "minor") 
    @all.push new Element("Gingko Biloba", "microgram", "minor") 
    @all.push new Element("Lutein", "microgram", "minor") 
    @all.push new Element("Alpha Carotene", "microgram", "minor") 
    @all.push new Element("Vanadium", "microgram", "minor")     
    @all.push new Element("Isoleucine", "g", "breakdown") 
    @all.push new Element("Leucine", "g", "breakdown") 
    @all.push new Element("Lysine", "g", "breakdown") 
    @all.push new Element("Methionine", "g", "breakdown") 
    @all.push new Element("Phenylalanine", "g", "breakdown") 
    @all.push new Element("Threonine", "g", "breakdown") 
    @all.push new Element("Tryptophan", "g", "breakdown") 
    @all.push new Element("Valine", "g", "breakdown") 
    @all.push new Element("Histidine", "g", "breakdown") 
    @all.push new Element("Alanine", "g", "breakdown") 
    @all.push new Element("Arginine", "g", "breakdown") 
    @all.push new Element("Aspartic acid", "g", "breakdown") 
    @all.push new Element("Cysteine", "g", "breakdown") 
    @all.push new Element("Glutamic acid", "g", "breakdown") 
    @all.push new Element("Glycine", "g", "breakdown") 
    @all.push new Element("Proline", "g", "breakdown") 
    @all.push new Element("Serine", "g", "breakdown") 
    @all.push new Element("Tyrosine", "g", "breakdown") 

    # Others
    @all.push new Element("Ash", "g") 
    @all.push new Element("Alpha Lipoic acid", "g")
    @all.push new Element("Astragalus", "g")
    @all.push new Element("Barberry", "g")
    @all.push new Element("Betacarotene", "g")
    @all.push new Element("Bilberry", "g")
    @all.push new Element("Boron", "g")
    @all.push new Element("Buchu", "g")
    @all.push new Element("Calories", "g")
    @all.push new Element("Celery", "g")
    @all.push new Element("Cholecalciferol", "g")
    @all.push new Element("Cholesterol", "g")
    @all.push new Element("Citrus bioflavonoids extract", "g")
    @all.push new Element("Co-Enzyme Q10", "g")
    @all.push new Element("Cryptoxanthin", "g")
    @all.push new Element("Cystine", "g")
    @all.push new Element("D-alpha tocopheryl acid succinate", "g")
    @all.push new Element("Damiana", "g")
    @all.push new Element("Docosahexaenoic acid", "g")
    @all.push new Element("Eicosapentaenoic acid", "g")
    @all.push new Element("Fennel", "g")
    @all.push new Element("Ginger", "g")
    @all.push new Element("Globe artichoke", "g")
    @all.push new Element("Gotu kola", "g")
    @all.push new Element("Grapeseed", "g")
    @all.push new Element("Green tea", "g")
    @all.push new Element("Hawthorn", "g")
    @all.push new Element("Horsetail", "g")
    @all.push new Element("Inositol", "g")
    @all.push new Element("Lysine hydrochloride", "g")
    @all.push new Element("Methylsulfonylmethane", "g")
    @all.push new Element("Nicotinamide", "g")
    @all.push new Element("Oats", "g")
    @all.push new Element("Omega-6 Fatty Acids", "g")
    @all.push new Element("PABA", "g")
    @all.push new Element("Papaya", "g")
    @all.push new Element("Parsley", "g")
    @all.push new Element("Rutin", "g")
    @all.push new Element("Sarsaparilla", "g")
    @all.push new Element("Saw palmetto", "g")
    @all.push new Element("Silica", "g")
    @all.push new Element("Spearmint oil", "g")
    @all.push new Element("St. Mary’s thistle", "g")
    @all.push new Element("Tomato", "g")
    @all.push new Element("Zeaxanthin", "g")

    this[element.name] = element for element in @all
      

